<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <PackageId>SweetMeSoft.Captcha</PackageId>
    <Version>1.10.104</Version>
    <Title>SweetMeSoft Captcha</Title>
    <Description>SweetMeSoft Captcha Library is for solve the most of captchas automatically</Description>
    <PackageTags>captcha, 2captcha, recaptcha, hcaptcha</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="logo_sq_512.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SweetMeSoft.Base\SweetMeSoft.Base.csproj" />
    <ProjectReference Include="..\SweetMeSoft.Tools\SweetMeSoft.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TwoCaptcha">
      <HintPath>..\Libraries\TwoCaptcha.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
