<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <PackageId>SweetMeSoft.Middleware</PackageId>
    <Version>1.10.110</Version>
    <Title>SweetMeSoft Middleware</Title>
    <Description>SweetMeSoft Middleware Library is a compilation of different middlewares for .Net core</Description>
    <PackageTags>aspnetcore, middleware, errorhandling, requestlogging, servicefactory</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="logo_sq_512.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SweetMeSoft.Tools\SweetMeSoft.Tools.csproj" />
  </ItemGroup>

</Project>
