<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <PackageId>SweetMeSoft.Tools</PackageId>
    <Version>1.10.133</Version>
    <Title>SweetMeSoft Tools</Title>
    <Description>SweetMeSoft Tools Library is a compilation of basic tools to use</Description>
    <PackageTags>tools, utilities, helpers, security, email, reflection, validation</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="logo_sq_512.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SweetMeSoft.Base\SweetMeSoft.Base.csproj" />
  </ItemGroup>

</Project>
