<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <PackageId>SweetMeSoft.Connectivity</PackageId>
    <Version>1.10.131</Version>
    <Title>SweetMeSoft Connectivity</Title>
    <Description>SweetMeSoft Connectivity Library is a compilation of easy to use tools to connect with ThirdParties services and APIs</Description>
    <PackageTags>http, api, connectivity, httpclient, web, request</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="logo_sq_512.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SweetMeSoft.Base\SweetMeSoft.Base.csproj" />
  </ItemGroup>

</Project>
