<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <PackageId>SweetMeSoft.Base</PackageId>
    <Version>1.10.146</Version>
    <Title>SweetMeSoft Base</Title>
    <Description>SweetMeSoft Base Library is the base of SweetMeSoft Libraries</Description>
    <PackageTags>base, helpers, attributes, connectivity, gcp, email, stream</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="logo_sq_512.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>

</Project>
